___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [4]:

np.version.version
print(np.__version__)
print(np.show_config())

1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

Створити вектор з 10 елементів, заповнений одиницями:

In [10]:
a = np.empty(10)
a.fill(1)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [11]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Створити матрицю 5 на 5, заповнену нулями:

In [13]:
c = np.zeros((5, 5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [25]:
d = np.random.randint(10, size=20)
print(d)
np.argwhere(d > 0)

[5 2 1 4 3 2 3 5 0 7 1 6 3 4 6 9 3 0 3 4]


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [18],
       [19]])

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [28]:
print(d.mean())
print(np.median(d))
print(d.std())

3.55
3.0
2.2688102609076854


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [41]:
m1 = np.random.randint(10, size=(4, 2))
m2 = np.random.randint(10, size=(2, 2))

C = np.dot(m1, m2)

print(m1, "", m2)
print(" ")
print(m2)
print(" ")
print(C)

[[1 6]
 [5 6]
 [7 6]
 [2 5]]  [[9 5]
 [0 5]]
 
[[9 5]
 [0 5]]
 
[[ 9 35]
 [45 55]
 [63 65]
 [18 35]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [48]:
A = C.flatten()
print(A)
print(A.max())
print(A.argmax())
A[A.argmax()] = 0
print(A)

[ 9 35 45 55 63 65 18 35]
65
5
[ 9 35 45 55 63  0 18 35]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [51]:
R1 = np.corrcoef(A)
R1

1.0

Дано матрицю. Знайти ранг матриці:

In [52]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [53]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [55]:
np.linalg.eig(a)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        ,  0.31386258+0.47450898j,
          0.31386258-0.47450898j],
        [ 0.41502436+0.j        ,  0.07049527-0.4090732j ,
          0.07049527+0.4090732j ],
        [ 0.8010734 +0.j        , -0.7099444 +0.j        ,
         -0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [58]:
a = np.random.randint(0,10,50)
print(a)
counts = np.bincount(a)
print(np.argmax(counts))

[0 4 5 3 9 3 0 6 7 0 6 2 4 4 8 1 7 1 1 2 9 7 4 4 7 9 3 9 6 8 4 1 3 0 2 3 5
 0 1 6 7 8 0 4 1 9 6 5 8 6]
4


Виведіть лише парні числа, що діляться на 5:

In [67]:
a = np.random.randint(0, 10, 50)

print(a)
c = a[1::2]

print(c[c % 5 == 0])


[6 0 0 7 9 2 3 8 6 7 1 3 6 1 6 5 3 3 4 2 3 3 9 0 4 0 2 3 1 0 7 4 6 0 2 5 8
 1 3 8 9 0 0 3 6 3 1 5 1 2]
[0 5 0 0 0 0 5 0 5]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [72]:
A = np.array([[2, 5], [1, -10]])
B = np.array([1, 3])
X = np.linalg.inv(A).dot(B)
X2 = np.linalg.solve(A,B)
print(X)
print(X2)

[ 1.  -0.2]
[ 1.  -0.2]
